// GENERATED by scripts/build.mjs — do NOT edit by hand.
// Edit the authored sources (e.g. src/content/greenhouse.js + its imports) and run `npm run build`.
"use strict";
(() => {
  // ── src/lib/config.js ──
// Central config. The extension talks only to the production API; the connect
// flow lives on the marketing origin. Kept in one place so a fork pointing at
// a local backend only edits here.
const API_BASE = "https://api.aptly.fyi";
const WEB_BASE = "https://aptly.fyi";
const CONNECT_URL = `${WEB_BASE}/extension/connect`;

// Greenhouse demographic / sensitive fields are NEVER auto-filled unless the
// user opts in. Matched against the lowercased question text.
const SENSITIVE_PATTERNS = [
  "race",
  "ethnicity",
  "gender",
  "veteran",
  "disability",
  "sexual orientation",
  "transgender",
];
const SALARY_PATTERNS = ["salary", "compensation", "pay expectation", "desired pay"];

  // ── src/content/shared.js ──
// Shared field-detection + filling helpers. The field model is platform-
// agnostic, so multiple adapters reuse it: the standard-DOM ATSes (Greenhouse,
// Lever, Ashby, SmartRecruiters) via content/greenhouse.js, and the
// experimental Workday adapter via content/workday.js. NOTHING here mutates the
// host page except value-filling triggered by an explicit user action in the
// popup.



// Categories the popup colour-codes:
//   contact   → fill from profile, high confidence (green)
//   resume    → resume content / file upload
//   qa        → free/clustered question (yellow if suggested, red if novel)
const CONTACT_FIELDS = {
  name: ["full name", "your name", "name"],
  first_name: ["first name", "given name", "legal first name"],
  last_name: ["last name", "family name", "surname", "legal last name"],
  email: ["email"],
  phone: ["phone", "mobile", "telephone"],
  linkedin: ["linkedin"],
  github: ["github"],
  portfolio: ["portfolio", "website", "personal site"],
  location: ["location", "city", "where are you based", "current location"],
  country: ["country"],
};

// Compliance / EEO questions → profile keys. Sponsorship + work-authorization
// are "standard" answers; the EEO four are demographic and only filled when the
// user explicitly set them (see complianceValue). Matched against the
// normalized question text; order matters (most specific first).
const COMPLIANCE_FIELDS = {
  requires_sponsorship: [
    "require sponsorship",
    "need sponsorship",
    "visa sponsorship",
    "sponsorship now or in the future",
    "will you now or in the future require",
  ],
  work_authorization: [
    "authorized to work",
    "legally authorized",
    "work authorization",
    "eligible to work",
  ],
  veteran_status: ["veteran", "protected veteran"],
  disability_status: ["disability", "disabled"],
  race_ethnicity: ["race", "ethnicity", "hispanic or latino"],
  gender: ["gender", "sex"],
};

// The EEO keys we NEVER auto-select unless the user explicitly set a value.
const EEO_KEYS = new Set([
  "veteran_status",
  "disability_status",
  "race_ethnicity",
  "gender",
]);

function norm(s) {
  return (s || "").trim().toLowerCase().replace(/\s+/g, " ");
}

// Find the human-readable question for an input by walking the DOM the way
// Greenhouse structures it: <label for=id>, then an ancestor label, then the
// nearest preceding label-ish text.
function questionFor(el) {
  const id = el.getAttribute("id");
  if (id) {
    const lab = document.querySelector(`label[for="${CSS.escape(id)}"]`);
    if (lab && lab.textContent.trim()) return clean(lab.textContent);
  }
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) return clean(ariaLabel);
  const labelledby = el.getAttribute("aria-labelledby");
  if (labelledby) {
    const node = document.getElementById(labelledby);
    if (node) return clean(node.textContent);
  }
  const wrapLabel = el.closest("label");
  if (wrapLabel && wrapLabel.textContent.trim()) return clean(wrapLabel.textContent);
  // Greenhouse wraps fields in a container; grab its label/legend.
  const field = el.closest(".field, [class*='field'], fieldset, .application-question");
  if (field) {
    const lab = field.querySelector("label, legend, .label");
    if (lab && lab.textContent.trim()) return clean(lab.textContent);
  }
  return clean(el.getAttribute("name") || el.getAttribute("placeholder") || "");
}

function clean(text) {
  return (text || "")
    .replace(/\*/g, "")
    .replace(/\(required\)/gi, "")
    .replace(/\s+/g, " ")
    .trim();
}

// ── Page-wide, selector-agnostic field detection ───────────────────────────
// Works on both the old boards.greenhouse.io <form> markup and the new
// job-boards.greenhouse.io React SPA (which may not wrap fields in a <form>).
// Pure functions (DOM-in, value-out) so they're unit-testable with a stub DOM.

const SKIP_TYPES = new Set(["hidden", "submit", "button", "reset", "image"]);
const SKIP_PLACEHOLDER = /search|subscribe|newsletter|language|filter|keyword|find jobs/i;
const SKIP_NAME = /search|query|locale|lang|subscribe|newsletter/i;

function isVisible(el) {
  // offsetParent is null for display:none + detached nodes; honour aria-hidden
  // and zero-size, with a client-rect fallback for position:fixed elements.
  if (el.getAttribute("aria-hidden") === "true") return false;
  if (el.offsetParent != null) return true;
  const r = el.getBoundingClientRect ? el.getBoundingClientRect() : { width: 0, height: 0 };
  return r.width > 0 && r.height > 0;
}

function inChrome(el) {
  return !!(el.closest && el.closest("nav, header, footer, [role='navigation'], [role='search']"));
}

function isApplicationInput(el) {
  const tag = (el.tagName || "").toLowerCase();
  if (!["input", "select", "textarea"].includes(tag)) return false;
  if (el.disabled) return false;
  const t = (el.getAttribute("type") || "").toLowerCase();
  if (SKIP_TYPES.has(t)) return false;
  if (tag === "input" && (t === "search" || el.getAttribute("role") === "searchbox")) return false;
  if (SKIP_PLACEHOLDER.test(el.getAttribute("placeholder") || "")) return false;
  if (SKIP_NAME.test(el.getAttribute("name") || "")) return false;
  if (inChrome(el)) return false;
  if (!isVisible(el)) return false;
  return true;
}

function fieldType(el) {
  const tag = el.tagName.toLowerCase();
  if (tag === "textarea") return "text";
  if (tag === "select") return "select";
  if (tag === "input") {
    const t = (el.getAttribute("type") || "text").toLowerCase();
    if (t === "radio") return "radio";
    if (t === "checkbox") return "checkbox";
    if (t === "file") return "file";
    if (t === "date") return "date";
    return "text";
  }
  return "text";
}

function isSensitive(question) {
  const q = norm(question);
  return SENSITIVE_PATTERNS.some((p) => q.includes(p));
}

function isSalary(question) {
  const q = norm(question);
  return SALARY_PATTERNS.some((p) => q.includes(p));
}

function contactKeyFor(question) {
  const q = norm(question);
  for (const [key, patterns] of Object.entries(CONTACT_FIELDS)) {
    if (patterns.some((p) => q === p || q.includes(p))) return key;
  }
  return null;
}

// Map a contact key (from contactKeyFor) to the matching profile value. Shared
// by every adapter so they fill name/email/links identically. Pure.
function contactValue(key, p) {
  if (!p) return "";
  switch (key) {
    case "name":
      return p.name;
    case "first_name":
      return (p.name || "").split(" ")[0];
    case "last_name":
      return (p.name || "").split(" ").slice(1).join(" ");
    case "email":
      return p.email;
    case "phone":
      return p.phone;
    case "linkedin":
      return p.linkedin;
    case "github":
      return p.github;
    case "portfolio":
      return p.portfolio;
    case "location":
      return p.location;
    case "country":
      // Profile has no dedicated country field; fill only if one is present
      // (never fabricated from location). Empty → the field is left untouched.
      return p.country || "";
    default:
      return "";
  }
}

// Which compliance/EEO key (if any) a question is asking about.
function complianceKeyFor(question) {
  const q = norm(question);
  for (const [key, patterns] of Object.entries(COMPLIANCE_FIELDS)) {
    if (patterns.some((p) => q.includes(p))) return key;
  }
  return null;
}

// The profile value for a compliance key, or "" when unset. EEO keys return ""
// unless the user explicitly set them — the caller then leaves the field
// untouched (never auto-selects a demographic answer the user didn't choose).
function complianceValue(key, p) {
  if (!p) return "";
  return (p[key] || "").trim();
}

// React-friendly value setters: set via the native descriptor then dispatch
// input/change so controlled components pick up the new value.
function setInputValue(el, value) {
  const proto = el.tagName === "TEXTAREA" ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
  const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
  if (setter) setter.call(el, value);
  else el.value = value;
  el.dispatchEvent(new Event("input", { bubbles: true }));
  el.dispatchEvent(new Event("change", { bubbles: true }));
}

function setSelectValue(el, value) {
  const v = norm(value);
  const opt = Array.from(el.options).find(
    (o) => norm(o.textContent) === v || norm(o.value) === v,
  );
  if (opt) {
    el.value = opt.value;
    el.dispatchEvent(new Event("change", { bubbles: true }));
    return true;
  }
  return false;
}

// Set a native <select> by matching `value` against option TEXT (loose, via
// matchOptionByText) — for compliance/EEO dropdowns whose option wording varies
// across ATSes ("Yes, I require sponsorship" vs the saved "Yes"). Returns true
// only if an option actually matched + was selected. Never selects a fallback.
function setSelectByText(el, value) {
  if (!value) return false;
  const options = Array.from(el.options || []);
  const match = matchOptionByText(options, value);
  if (!match) return false;
  el.value = match.value;
  el.dispatchEvent(new Event("change", { bubbles: true }));
  return true;
}

// Match a desired value against a list of option-like nodes by their visible
// text. Used by the Workday adapter for custom (non-<select>) dropdowns, where
// the trigger opens a [role="listbox"] of [role="option"] nodes. Pure and
// DOM-light (only reads `.textContent`) so it's unit-testable with a stub DOM.
// Returns the matching node or null — never guesses past a guarded contains().
function matchOptionByText(options, value) {
  const v = norm(value);
  if (!v) return null;
  const texts = options.map((o) => norm(o && o.textContent));
  // 1) Exact (normalized) match — the safe, common case. Wins over any loose
  //    match regardless of option order (e.g. "No" beats "Not sure").
  let i = texts.findIndex((t) => t === v);
  if (i >= 0) return options[i];
  // 2) Loose containment either direction, length-guarded to avoid 1-char
  //    noise. Handles a Workday label carrying a longer/shorter form than the
  //    saved value (e.g. "United States of America" vs "United States").
  if (v.length >= 2) {
    i = texts.findIndex((t) => t.length >= 2 && (t.includes(v) || v.includes(t)));
    if (i >= 0) return options[i];
  }
  return null;
}

function clickRadioOrCheckbox(groupEls, value) {
  const v = norm(value);
  for (const el of groupEls) {
    const q = norm(questionFor(el)) || norm(el.value);
    if (q === v || q.includes(v) || norm(el.value) === v) {
      el.click(); // click triggers React handlers; .checked= doesn't
      return true;
    }
  }
  return false;
}

// ── Deep (shadow-DOM-piercing) query ────────────────────────────────────────
// querySelectorAll on `root` PLUS a recursive descent into every element's OPEN
// .shadowRoot, concatenated. Modern ATSes (SmartRecruiters among them) can mount
// form fields inside open shadow roots, which a plain document.querySelectorAll
// cannot see — that's how detection can find 0 fields on a page that clearly has
// inputs. NOTE: CLOSED shadow roots expose no .shadowRoot and are unreachable to
// ANY extension; nothing we can do about those.
function queryAllDeep(root, selector) {
  const out = [];
  const visit = (node) => {
    if (!node || typeof node.querySelectorAll !== "function") return;
    for (const el of node.querySelectorAll(selector)) out.push(el);
    // Descend into the open shadow root of every element in this subtree.
    for (const el of node.querySelectorAll("*")) {
      if (el.shadowRoot) visit(el.shadowRoot);
    }
  };
  visit(root);
  return out;
}

const DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

// ── Job-description extraction (read-only) ──────────────────────────────────
// Best-effort visible JD text from the CURRENT page, for the popup's review
// panel. NEVER mutates the page. Prefers obvious description containers, then
// falls back to the largest visible text block. Length-capped so a giant page
// can't bloat the message. The popup escapes this before rendering — it is
// untrusted third-party page content.
const JD_MAX_CHARS = 4000;

// Best-first containers that usually wrap a posting's description. The `i`
// flag makes the attribute substring match case-insensitive (CSS L4, Chrome).
const JD_CONTAINER_SELECTORS = [
  "[data-automation-id*='jobPostingDescription' i]", // Workday
  "[data-automation-id*='description' i]",
  "[class*='job-description' i]",
  "[class*='jobdescription' i]",
  "[class*='posting-description' i]",
  "[id*='job-description' i]",
  "[class*='description' i]",
  "article",
  "[role='main']",
  "main",
];

function visibleText(el) {
  if (!el || !isVisible(el)) return "";
  // innerText (not textContent) so hidden subtrees are excluded and block
  // breaks are preserved; collapse runaway blank lines.
  return (el.innerText || el.textContent || "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function extractJobDescription(root = document) {
  let best = "";
  for (const sel of JD_CONTAINER_SELECTORS) {
    let candidates = [];
    try {
      candidates = queryAllDeep(root, sel);
    } catch (_) {
      candidates = [];
    }
    for (const el of candidates) {
      if (inChrome(el)) continue; // skip nav/header/footer/search chrome
      const t = visibleText(el);
      if (t.length > best.length) best = t;
    }
    // A solid hit from a specific selector is enough — stop before the generic
    // [class*=description]/main catch-alls over-grab the whole layout.
    if (best.length >= 600) break;
  }
  // Fallback: largest visible text among a FEW structural blocks (then body).
  // Deliberately not every <div> — innerText forces layout, so keep it bounded.
  if (best.length < 200) {
    for (const el of queryAllDeep(root, "main, [role='main'], article, section")) {
      if (inChrome(el)) continue;
      const t = visibleText(el);
      if (t.length > best.length) best = t;
    }
    if (best.length < 200 && root && root.body) {
      const bodyText = visibleText(root.body);
      if (bodyText.length > best.length) best = bodyText;
    }
  }
  return best.slice(0, JD_MAX_CHARS);
}

// ── Resume file attach (user-initiated, part of "Start filling") ────────────
// Decode the base64 DOCX (fetched with the bearer token by the service worker —
// the binary crosses the messaging boundary as base64 because Chrome messaging
// is JSON-serialized) back into a File. atob is available in content scripts.
function base64ToFile(b64, name, mime) {
  const binary = atob(b64 || "");
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return new File([bytes], name || "Aptly_Resume.docx", { type: mime || DOCX_MIME });
}

// Attach a File to an <input type=file> the way the browser would — via a
// DataTransfer — then fire input+change so React/controlled widgets notice.
// Returns true only if the input actually holds the file afterwards.
function attachFileToInput(input, file) {
  try {
    const dt = new DataTransfer();
    dt.items.add(file);
    input.files = dt.files;
    input.dispatchEvent(new Event("input", { bubbles: true }));
    input.dispatchEvent(new Event("change", { bubbles: true }));
    return !!(input.files && input.files.length > 0);
  } catch (_) {
    return false;
  }
}

// Fallback for styled drop-zones: synthesise a drag-and-drop carrying the file.
// Best-effort — we can't confirm the site accepted it — so callers prefer
// attachFileToInput when a real input exists and only fall here if that fails.
function dropFileOnZone(zone, file) {
  if (!zone) return false;
  try {
    const dt = new DataTransfer();
    dt.items.add(file);
    for (const type of ["dragenter", "dragover", "drop"]) {
      zone.dispatchEvent(new DragEvent(type, { bubbles: true, cancelable: true, dataTransfer: dt }));
    }
    return true;
  } catch (_) {
    return false;
  }
}

// The visible drop target wrapping a (often hidden) file input.
function dropZoneFor(input) {
  return (
    (input.closest &&
      input.closest("label, [class*='upload'], [class*='drop'], [class*='attach'], [class*='file']")) ||
    input.parentElement ||
    null
  );
}

// True if `el` is a file input we'd attach a RESUME to — an <input type=file>
// that is NOT an obvious photo/avatar/image picker. Deliberately does NOT check
// visibility: resume inputs are routinely display:none behind a drop-zone, so
// detection skips them but attach must still find them. Pure → unit-testable.
function isResumeFileInput(el) {
  const tag = (el.tagName || "").toLowerCase();
  const type = (el.getAttribute("type") || "").toLowerCase();
  if (tag !== "input" || type !== "file") return false;
  const hay = `${el.getAttribute("name") || ""} ${el.getAttribute("id") || ""}`.toLowerCase();
  if (/photo|avatar|image|picture|headshot|logo|profile.?pic/.test(hay)) return false;
  // Reject image-only pickers, but keep ones that also allow docs/pdf.
  const accept = (el.getAttribute("accept") || "").toLowerCase();
  if (accept && /image\//.test(accept) && !/(pdf|word|document|officedocument|\.docx?|\.pdf)/.test(accept)) {
    return false;
  }
  return true;
}

// All resume-eligible file inputs under `root`, piercing open shadow roots.
function findFileInputs(root) {
  return queryAllDeep(root, "input[type='file']").filter(isResumeFileInput);
}

  // ── src/content/greenhouse.js ──
// Standard-DOM ATS content script. Despite the filename (kept as-is this
// release to avoid a churny rename), this now serves every ATS that exposes a
// conventional <input>/<select>/<textarea> form: Greenhouse, Lever, Ashby, and
// SmartRecruiters. Detection + fill are selector-agnostic (see shared.js), so
// one script covers all four. Workday is handled separately by workday.js
// because its custom-widget DOM needs bespoke fillers.
//
// Detects the application form, reports the field count to the popup via the
// badge, and — only when the user clicks "Start filling" in the popup — fills
// fields it can and colour-codes each one.
//
// Hard rules: never submits; never auto-fills sensitive/demographic fields
// without opt-in; never modifies the page beyond filling values + a tiny
// status dot next to each touched field.



const STATE = {
  fields: [],
  filledOnce: false,
  lastCount: -1,
};

const DOT_CLASS = "aptly-status-dot";
const COLORS = { green: "#16a34a", yellow: "#eab308", red: "#dc2626" };
const LOG = "[Aptly]";

// Minimum form-like inputs for a page to count as an application form. Fewer
// than this is probably just a search box / login, not an application.
const MIN_FIELDS = 3;

// Selector-AGNOSTIC, shadow-DOM-piercing detection. We ALWAYS scan the whole
// document with queryAllDeep (which descends into OPEN shadow roots) and filter
// with isApplicationInput. This is a superset of any single-<form> scan, so it
// can't under-count, and it removes the wrong-form hijack where a stray
// non-application <form> with >=3 inputs (search/login/newsletter) used to
// satisfy the threshold and block the real apply fields — e.g. SmartRecruiters,
// whose fields (id="first-name-input", …) are mounted in an open shadow root.
// Works on old Greenhouse <form> markup, the React SPA, Lever/Ashby, and
// SmartRecruiters alike. (Closed shadow roots are unreachable to any extension.)
function collectFields() {
  const els = queryAllDeep(document, "input, select, textarea").filter(isApplicationInput);
  // Group radios/checkboxes by name so a group counts as one question.
  const seenGroups = new Set();
  const fields = [];
  for (const el of els) {
    const type = fieldType(el);
    if ((type === "radio" || type === "checkbox") && el.name) {
      if (seenGroups.has(el.name)) continue;
      seenGroups.add(el.name);
      fields.push({ el, type, group: els.filter((x) => x.name === el.name) });
    } else {
      fields.push({ el, type, group: null });
    }
  }
  return fields;
}

function setDot(el, color) {
  let dot = el.parentElement?.querySelector(`.${DOT_CLASS}`);
  if (!dot) {
    dot = document.createElement("span");
    dot.className = DOT_CLASS;
    dot.style.cssText =
      "display:inline-block;width:8px;height:8px;border-radius:50%;margin-left:6px;vertical-align:middle;";
    el.insertAdjacentElement("afterend", dot);
  }
  dot.style.background = color;
  dot.title =
    color === COLORS.green
      ? "Filled from your Aptly profile"
      : color === COLORS.yellow
        ? "Suggested from a previous application — please review"
        : "Needs your input";
}

// Run detection, push the count to the background (badge) + log when it
// changes. `hasForm` is true once we clear the MIN_FIELDS threshold — the popup
// keys off this, not off the presence of a literal <form> element.
function detectFormFields(reason) {
  STATE.fields = collectFields();
  const count = STATE.fields.length;
  const hasForm = count >= MIN_FIELDS;
  if (count !== STATE.lastCount) {
    console.log(`${LOG} ${reason}: ${count} field${count === 1 ? "" : "s"} found`);
    STATE.lastCount = count;
  }
  chrome.runtime.sendMessage({ type: "GH_FIELDS", count, hasForm, url: location.href });
  return count;
}

let detectTimeout = null;

// The new Greenhouse pages mount the form after initial load (React). Watch the
// whole body and re-detect, debounced, until the DOM settles.
function init() {
  console.log(`${LOG} Content script loaded on ${location.href}`);
  detectFormFields("Initial form detection");

  const observer = new MutationObserver(() => {
    // Re-validate previously-filled fields; mark reverted ones red.
    if (STATE.filledOnce) {
      for (const f of STATE.fields) {
        if (f.type === "text" && f.filled && f.el && !f.el.value) setDot(f.el, COLORS.red);
      }
    }
    clearTimeout(detectTimeout);
    detectTimeout = setTimeout(() => {
      console.log(`${LOG} DOM changed, re-detecting...`);
      detectFormFields("After re-detection");
    }, 300);
  });
  observer.observe(document.body, { childList: true, subtree: true });
}

async function fillFields({ profile, runId, prefs }) {
  const summary = { green: 0, yellow: 0, red: 0, sensitive: 0, file: 0, fileAttached: 0, attachedName: "" };
  for (const f of STATE.fields) {
    const question = questionFor(f.el);
    if (!question) continue;

    // File inputs are handled by the dedicated resume-attach pass after this
    // loop (it also covers HIDDEN inputs behind drop-zones, which detection
    // skips because they aren't visible).
    if (f.type === "file") continue;

    // Compliance / EEO: sponsorship + work-auth + the demographic four. We fill
    // ONLY when the user explicitly saved a value; a blank profile value leaves
    // the field UNTOUCHED — we never auto-select a demographic answer the user
    // didn't choose. Handled before the generic sensitive-skip below so an
    // explicitly-set EEO value is honoured.
    const cKey = complianceKeyFor(question);
    if (cKey && profile) {
      const cValue = complianceValue(cKey, profile);
      if (cValue) {
        const ok = applyComplianceValue(f, cValue);
        setDot(f.el, ok ? COLORS.green : COLORS.yellow);
        if (ok) f.filled = true;
        ok ? summary.green++ : summary.yellow++;
        continue;
      }
      // No saved value → leave it for the user. Mark yellow (review) and, for
      // the EEO four, count it as a deliberately-blank sensitive field.
      setDot(f.el, COLORS.yellow);
      if (EEO_KEYS.has(cKey)) summary.sensitive++;
      else summary.yellow++;
      continue;
    }

    // Any other sensitive/demographic phrasing we recognise but don't have a
    // profile key for: never auto-fill unless opted in.
    if (isSensitive(question) && !prefs.rememberDemographics) {
      setDot(f.el, COLORS.yellow);
      summary.sensitive++;
      continue;
    }

    // Contact info → profile (high confidence).
    const key = contactKeyFor(question);
    if (key && profile) {
      const value = contactValue(key, profile);
      if (value) {
        applyValue(f, value);
        f.filled = true;
        setDot(f.el, COLORS.green);
        summary.green++;
        continue;
      }
    }

    // Everything else → QA lookup (clustered learning loop). Salary asks
    // before saving but can still be suggested if previously answered.
    try {
      const res = await chrome.runtime.sendMessage({
        type: "QA_LOOKUP",
        question_text: question,
        field_type: f.type,
      });
      if (res && res.answer) {
        applyValue(f, res.answer);
        f.filled = true;
        setDot(f.el, COLORS.yellow); // suggested → review
        summary.yellow++;
      } else {
        setDot(f.el, COLORS.red);
        summary.red++;
      }
    } catch (_) {
      setDot(f.el, COLORS.red);
      summary.red++;
    }
  }
  await attachResume(runId, document, summary);
  STATE.filledOnce = true;
  return summary;
}

function applyValue(f, value) {
  if (f.type === "select") return setSelectValue(f.el, value);
  if (f.type === "radio" || f.type === "checkbox")
    return clickRadioOrCheckbox(f.group || [f.el], value);
  return setInputValue(f.el, value);
}

// Compliance/EEO answers are almost always SELECT dropdowns or radio groups
// whose option wording varies by ATS, so match by TEXT (loose). Returns true
// only if an option actually matched — a non-match leaves the field untouched.
function applyComplianceValue(f, value) {
  if (f.type === "select") return setSelectByText(f.el, value);
  if (f.type === "radio" || f.type === "checkbox")
    return clickRadioOrCheckbox(f.group || [f.el], value);
  return setInputValue(f.el, value);
}

// Resume auto-attach: the service worker fetches the tailored DOCX (it holds the
// bearer token) and returns it base64-encoded; we decode it here and attach it
// to every resume file input — including hidden ones behind a styled drop-zone.
// User-initiated (part of Start filling); NEVER submits. Attached inputs go
// green (summary.fileAttached); on any failure we leave the field yellow and the
// popup shows the manual-download fallback (summary.file).
async function attachResume(runId, root, summary) {
  const inputs = findFileInputs(root);
  if (!inputs.length) return;
  if (!runId) {
    for (const el of inputs) {
      setDot(el, COLORS.yellow);
      summary.file++;
    }
    return;
  }
  let data = null;
  try {
    data = await chrome.runtime.sendMessage({ type: "RESUME_FILE", runId });
  } catch (_) {
    data = null;
  }
  if (!data || !data.base64) {
    for (const el of inputs) {
      setDot(el, COLORS.yellow);
      summary.file++;
    }
    return;
  }
  const file = base64ToFile(data.base64, data.filename, data.mime);
  for (const el of inputs) {
    let ok = attachFileToInput(el, file);
    if (!ok) ok = dropFileOnZone(dropZoneFor(el), file);
    if (ok) {
      setDot(el, COLORS.green);
      summary.fileAttached++;
      summary.attachedName = data.filename;
    } else {
      setDot(el, COLORS.yellow);
      summary.file++;
    }
  }
}

// Messages from the popup / background.
chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  if (msg.type === "GH_PING") {
    // Re-detect FRESH on every popup open so a late-rendered form is picked up
    // even if the observer hasn't fired since the user last looked.
    const count = detectFormFields("Popup ping");
    sendResponse({ hasForm: count >= MIN_FIELDS, count, url: location.href });
    return true;
  }
  if (msg.type === "GH_FILL") {
    fillFields(msg.payload).then((summary) => sendResponse({ summary }));
    return true; // async
  }
  if (msg.type === "GET_PAGE_CONTEXT") {
    // Read-only context for the popup's review panel: the parsed JD + the
    // current field count + host. Never mutates the page.
    const fieldCount = detectFormFields("Popup context");
    let jdText = "";
    try {
      jdText = extractJobDescription(document);
    } catch (_) {
      jdText = "";
    }
    sendResponse({ jdText, fieldCount, host: location.host });
    return true;
  }
  return false;
});

init();

})();
