// Build for the no-bundler MV3 extension.
//
// Content scripts in MV3 are CLASSIC scripts — they cannot use ESM `import`.
// Our authored content code is split across modules (src/content/greenhouse.js
// imports src/content/shared.js, which imports src/lib/config.js), so it must
// be flattened before Chrome loads it. We do that with a tiny zero-dependency
// inliner (Node stdlib only — the sandbox has no bundler / no network) that
// resolves the relative import graph into one IIFE with all imports inlined.
//
// The popup (HTML page) and the background service worker (manifest
// "type":"module") CAN use ESM, so they're left as authored source.
//
// Outputs `content/greenhouse.js` at the extension root (committed so the
// package stays loadable-unpacked from the root with no build step), and a
// full `dist/` copy for zipping.
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const check = process.argv.includes("--check");

// Content-script entry points: authored ESM source → flat IIFE output (the
// path the manifest references). Add future content scripts here.
//   * greenhouse.js → standard-DOM ATSes (Greenhouse, Lever, Ashby, SmartRecruiters)
//   * workday.js    → experimental Workday adapter (separate match block)
const CONTENT_ENTRIES = [
  { src: "src/content/greenhouse.js", out: "content/greenhouse.js" },
  { src: "src/content/workday.js", out: "content/workday.js" },
];

async function exists(p) {
  try {
    await fs.access(path.join(root, p));
    return true;
  } catch {
    return false;
  }
}

// Matches `import ... from "path";` including multi-line specifier lists.
// (Only static, named/namespace/side-effect imports are used here — no
// dynamic import(), no `export {}` re-exports, no default exports.)
const IMPORT_RE = /import\s+[^;]*?\s+from\s+["']([^"']+)["'];?/g;
const SIDE_EFFECT_IMPORT_RE = /import\s+["']([^"']+)["'];?/g;

// Inline an ESM entry file + its relative imports into a single IIFE string.
// Modules are emitted dependency-first (post-order), each visited once.
async function bundle(entryRel) {
  const seen = new Set();
  const chunks = [];

  async function visit(fileAbs) {
    if (seen.has(fileAbs)) return;
    seen.add(fileAbs);
    let src = await fs.readFile(fileAbs, "utf8");
    const dir = path.dirname(fileAbs);

    // Recurse into relative deps first so they're defined before use.
    for (const re of [IMPORT_RE, SIDE_EFFECT_IMPORT_RE]) {
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(src))) {
        const spec = m[1];
        if (spec.startsWith(".")) await visit(path.resolve(dir, spec));
      }
    }

    // Strip the import statements + the `export ` declaration prefixes.
    src = src.replace(IMPORT_RE, "").replace(SIDE_EFFECT_IMPORT_RE, "");
    src = src.replace(/^[ \t]*export\s+(?=(?:const|let|var|function|async\s+function|class)\b)/gm, "");
    if (/^\s*export\b/m.test(src)) {
      throw new Error(`Unsupported export form in ${path.relative(root, fileAbs)} — inliner only handles \`export <decl>\``);
    }
    chunks.push(`  // ── ${path.relative(root, fileAbs)} ──\n${src.trim()}\n`);
  }

  await visit(path.join(root, entryRel));
  return (
    "// GENERATED by scripts/build.mjs — do NOT edit by hand.\n" +
    `// Edit the authored sources (e.g. ${entryRel} + its imports) and run \`npm run build\`.\n` +
    '"use strict";\n(() => {\n' +
    chunks.join("\n") +
    "\n})();\n"
  );
}

async function buildContentScripts() {
  for (const { src, out } of CONTENT_ENTRIES) {
    const code = await bundle(src);
    if (/^import\s/m.test(code)) {
      throw new Error(`Bundling failed: ${out} still contains an import statement.`);
    }
    const outAbs = path.join(root, out);
    await fs.mkdir(path.dirname(outAbs), { recursive: true });
    await fs.writeFile(outAbs, code);
    console.log(`bundled ${src} → ${out} (${code.length} bytes, import-free)`);
  }
}

// --check skips bundling (just validates the manifest references resolve
// against the already-committed outputs). A plain run rebuilds them first.
if (!check) {
  await buildContentScripts();
}

const manifest = JSON.parse(await fs.readFile(path.join(root, "manifest.json"), "utf8"));
const required = [
  manifest.background.service_worker,
  manifest.action.default_popup,
  ...manifest.content_scripts.flatMap((c) => c.js),
  ...Object.values(manifest.icons),
];

let ok = true;
for (const f of required) {
  if (!(await exists(f))) {
    console.error(`MISSING: ${f}`);
    ok = false;
  }
}
if (!ok) {
  console.error("Manifest references missing files.");
  process.exit(1);
}
console.log(`manifest v${manifest.manifest_version} OK — ${required.length} referenced files present`);

if (!check) {
  const dist = path.join(root, "dist");
  await fs.rm(dist, { recursive: true, force: true });
  await fs.mkdir(dist, { recursive: true });
  // `src` ships too: the popup (HTML) + background (ESM module worker) load
  // from src/ paths; only the content script uses the bundled `content/` copy.
  for (const rel of ["manifest.json", "src", "public", "content"]) {
    await fs.cp(path.join(root, rel), path.join(dist, rel), { recursive: true });
  }
  console.log("dist/ written — load unpacked from extension/ or extension/dist.");
}
