"""Bulk-loaded ATS token candidates across all supported platforms.

The runtime source of truth for ingest is the `sources` table. This
file is the *seed* for migration `0014_bulk_load_ats_tokens` and is
intentionally large — load wide, then let the existing ingest-time
validation + auto-prune machinery (`SOURCE_FAILURE_THRESHOLD`) sort
live boards from dead ones across successive scheduled runs.

Provenance: each list is a hand-curated set of company tokens drawn
from well-known public maintainers of ATS-board indices (e.g. the
many public GitHub repositories that aggregate Greenhouse/Lever
board tokens, the SmartRecruiters company-identifier directory, the
Workday tenant lists that recur in jobs-aggregator open-source
projects). The lists are split per platform because each ATS has
its own token shape:

  * Greenhouse / Lever / Ashby   — lowercase company slug, no
                                   structure (e.g. `stripe`).
  * SmartRecruiters              — case-sensitive identifier
                                   (e.g. `Bosch`); NOT a slug.
  * Workday                      — composite `tenant:dc:site`
                                   triple (e.g. `walmart:wd5:Careers`).
                                   Entries we couldn't form a complete
                                   triple for are deliberately omitted
                                   so the adapter never sees a half-
                                   formed token.

`INGEST_MAX_PER_RUN` (default 150) bounds each ingest pass; with a
few hundred extra source rows landing here, the rotation picks the
least-recently-checked ones first and the full set works through
across several scheduled passes — no single run stalls or runs over
budget.

Adding new tokens: drop them into the matching list below in
alphabetical order. Re-running the migration is a no-op for tokens
already present (idempotent by the `(source_type, token)` unique
constraint).
"""

from __future__ import annotations

# ── Greenhouse ──────────────────────────────────────────────────────────────
# `{token}` in https://boards.greenhouse.io/{token} — the public
# slug a company picks when they create their Greenhouse board.
GREENHOUSE_BULK_TOKENS: tuple[tuple[str, str], ...] = (
    # 1Password, 8x8, etc. — well-known Greenhouse boards. Display
    # names are the marketable forms so the admin UI reads cleanly
    # before the first ingest pass.
    ("1password", "1Password"),
    ("8x8", "8x8"),
    ("23andme", "23andMe"),
    ("a16z", "Andreessen Horowitz"),
    ("addepar", "Addepar"),
    ("affirm", "Affirm"),
    ("airtable", "Airtable"),
    ("algolia", "Algolia"),
    ("alteryx", "Alteryx"),
    ("amplitude", "Amplitude"),
    ("anchorage", "Anchorage Digital"),
    ("anduril", "Anduril Industries"),
    ("anyscale", "Anyscale"),
    ("appfolio", "AppFolio"),
    ("applovin", "AppLovin"),
    ("arc", "Arc"),
    ("arcadia", "Arcadia"),
    ("arkoselabs", "Arkose Labs"),
    ("articulate", "Articulate"),
    ("attentive", "Attentive"),
    ("auth0", "Auth0"),
    ("axoni", "Axoni"),
    ("benchling", "Benchling"),
    ("benevity", "Benevity"),
    ("benchmark", "Benchmark"),
    ("betterup", "BetterUp"),
    ("bigcommerce", "BigCommerce"),
    ("bigid", "BigID"),
    ("bigpanda", "BigPanda"),
    ("bill", "Bill.com"),
    ("bitgo", "BitGo"),
    ("blend", "Blend"),
    ("block", "Block"),
    ("blueoriginllc", "Blue Origin"),
    ("bolt", "Bolt"),
    ("box", "Box"),
    ("braze", "Braze"),
    ("brigit", "Brigit"),
    ("calendly", "Calendly"),
    ("calm", "Calm"),
    ("cameo", "Cameo"),
    ("carbon", "Carbon"),
    ("cardless", "Cardless"),
    ("carta", "Carta"),
    ("checkout", "Checkout.com"),
    ("chess", "Chess.com"),
    ("chime", "Chime"),
    ("circle", "Circle"),
    ("circleci", "CircleCI"),
    ("clearcover", "Clearcover"),
    ("clever", "Clever"),
    ("clickup", "ClickUp"),
    ("cloudflare", "Cloudflare"),
    ("cockroachlabs", "CockroachDB"),
    ("coursera", "Coursera"),
    ("credly", "Credly"),
    ("cribl", "Cribl"),
    ("crowdstrikeinc", "CrowdStrike"),
    ("crunchyrollllc", "Crunchyroll"),
    ("cruise", "Cruise"),
    ("cypressio", "Cypress.io"),
    ("databricks", "Databricks"),
    ("dave", "Dave"),
    ("deel", "Deel"),
    ("digitalocean", "DigitalOcean"),
    ("digitalturbine", "Digital Turbine"),
    ("discord", "Discord"),
    ("dnanexus", "DNAnexus"),
    ("docebo", "Docebo"),
    ("docusign", "DocuSign"),
    ("doximity", "Doximity"),
    ("duolingo", "Duolingo"),
    ("dynatrace", "Dynatrace"),
    ("eaze", "Eaze"),
    ("ebay", "eBay"),
    ("elastic", "Elastic"),
    ("evidation", "Evidation"),
    ("expel", "Expel"),
    ("fanatics", "Fanatics"),
    ("fastly", "Fastly"),
    ("faire", "Faire"),
    ("fetchrewards", "Fetch Rewards"),
    ("figma", "Figma"),
    ("fireblocks", "Fireblocks"),
    ("fivetran", "Fivetran"),
    ("flexport", "Flexport"),
    ("flock", "Flock Safety"),
    ("foursquare", "Foursquare"),
    ("front", "Front"),
    ("frontapp", "Front"),
    ("gemini", "Gemini"),
    ("github", "GitHub"),
    ("glean", "Glean"),
    ("global83", "Global83"),
    ("gong", "Gong"),
    ("grammarly", "Grammarly"),
    ("greenhouse", "Greenhouse"),
    ("grubhub", "Grubhub"),
    ("gusto", "Gusto"),
    ("hashicorp", "HashiCorp"),
    ("highspot", "Highspot"),
    ("hims", "Hims & Hers"),
    ("hippoinsurance", "Hippo Insurance"),
    ("hopin", "Hopin"),
    ("houzz", "Houzz"),
    ("hubspot", "HubSpot"),
    ("humu", "Humu"),
    ("imperfectfoods", "Imperfect Foods"),
    ("instabase", "Instabase"),
    ("instawork", "Instawork"),
    ("intercom", "Intercom"),
    ("invitae", "Invitae"),
    ("iterable", "Iterable"),
    ("jasper", "Jasper"),
    ("jellyvision", "Jellyvision"),
    ("jobber", "Jobber"),
    ("juniorachievement", "Junior Achievement"),
    ("justworks", "Justworks"),
    ("kard", "Kard"),
    ("keepsafe", "Keepsafe"),
    ("klaviyo", "Klaviyo"),
    ("kongbank", "Kong"),
    ("kraken", "Kraken Digital Asset Exchange"),
    ("krollllc", "Kroll"),
    ("latch", "Latch"),
    ("launchdarkly", "LaunchDarkly"),
    ("lemonade", "Lemonade"),
    ("lendingclub", "LendingClub"),
    ("linkedin", "LinkedIn"),
    ("liveperson", "LivePerson"),
    ("loom", "Loom"),
    ("lucid", "Lucid"),
    ("mailgun", "Mailgun"),
    ("mailchimp", "Mailchimp"),
    ("marqeta", "Marqeta"),
    ("masterclass", "MasterClass"),
    ("medallia", "Medallia"),
    ("modernhealth", "Modern Health"),
    ("module", "Module"),
    ("motive", "Motive"),
    ("netskope", "Netskope"),
    ("newrelic", "New Relic"),
    ("noom", "Noom"),
    ("nutanix", "Nutanix"),
    ("nuro", "Nuro"),
    ("nylas", "Nylas"),
    ("oktainc", "Okta"),
    ("oliveai", "Olive"),
    ("onepeloton", "Peloton"),
    ("opendoor", "Opendoor"),
    ("opensea", "OpenSea"),
    ("openstore", "OpenStore"),
    ("optimizely", "Optimizely"),
    ("oscar", "Oscar Health"),
    ("outreach", "Outreach"),
    ("palantirtech", "Palantir"),
    ("pantheon", "Pantheon"),
    ("paxos", "Paxos"),
    ("paypal", "PayPal"),
    ("peardeck", "Pear Deck"),
    ("pearvc", "Pear VC"),
    ("personio", "Personio"),
    ("pilot", "Pilot"),
    ("pinterest", "Pinterest"),
    ("placer", "Placer.ai"),
    ("podium", "Podium"),
    ("postman", "Postman"),
    ("pulley", "Pulley"),
    ("pure", "Pure Storage"),
    ("quantcast", "Quantcast"),
    ("qualtrics", "Qualtrics"),
    ("rappi", "Rappi"),
    ("redhat", "Red Hat"),
    ("redis", "Redis"),
    ("relay", "Relay Financial"),
    ("renaissancelearning", "Renaissance Learning"),
    ("rentpath", "RentPath"),
    ("reverb", "Reverb"),
    ("revolutionprep", "Revolution Prep"),
    ("rippling", "Rippling"),
    ("rivian", "Rivian"),
    ("roblox", "Roblox"),
    ("roku", "Roku"),
    ("salesloft", "Salesloft"),
    ("samsara", "Samsara"),
    ("scale", "Scale AI"),
    ("scribd", "Scribd"),
    ("sendbird", "Sendbird"),
    ("sentry", "Sentry"),
    ("seamlessai", "Seamless.AI"),
    ("shippo", "Shippo"),
    ("shopify", "Shopify"),
    ("sift", "Sift"),
    ("sigfig", "SigFig"),
    ("smartsheet", "Smartsheet"),
    ("snapinc", "Snap Inc."),
    ("snyk", "Snyk"),
    ("sofi", "SoFi"),
    ("sonatype", "Sonatype"),
    ("sourcegraph", "Sourcegraph"),
    ("spacex", "SpaceX"),
    ("spaceperspective", "Space Perspective"),
    ("spaceandtimedb", "Space and Time"),
    ("spotify", "Spotify"),
    ("squarespace", "Squarespace"),
    ("statsig", "Statsig"),
    ("stitchfix", "Stitch Fix"),
    ("strava", "Strava"),
    ("stubhub", "StubHub"),
    ("sumo", "Sumo Logic"),
    ("superhuman", "Superhuman"),
    ("surveymonkey", "SurveyMonkey"),
    ("sysdig", "Sysdig"),
    ("talkdesk", "Talkdesk"),
    ("tanium", "Tanium"),
    ("teachable", "Teachable"),
    ("techstars", "Techstars"),
    ("temporal", "Temporal"),
    ("textnow", "TextNow"),
    ("thirdrock", "Third Rock Ventures"),
    ("thoughtspot", "ThoughtSpot"),
    ("tinder", "Tinder"),
    ("tinyspeck", "Slack"),
    ("toast", "Toast"),
    ("tonal", "Tonal"),
    ("tripadvisor", "Tripadvisor"),
    ("twitch", "Twitch"),
    ("uber", "Uber"),
    ("udemy", "Udemy"),
    ("upgrade", "Upgrade"),
    ("upstart", "Upstart"),
    ("vail", "Vail Resorts"),
    ("vector", "Vector Solutions"),
    ("verkada", "Verkada"),
    ("vimeo", "Vimeo"),
    ("vroom", "Vroom"),
    ("warbyparker", "Warby Parker"),
    ("wayfair", "Wayfair"),
    ("wealthfront", "Wealthfront"),
    ("webflow", "Webflow"),
    ("weights-and-biases", "Weights & Biases"),
    ("whoop", "WHOOP"),
    ("wise", "Wise"),
    ("workato", "Workato"),
    ("xometry", "Xometry"),
    ("yelp", "Yelp"),
    ("zapier", "Zapier"),
    ("zendesk", "Zendesk"),
    ("zoominfo", "ZoomInfo"),
    ("zscaler", "Zscaler"),
)

# ── Lever ───────────────────────────────────────────────────────────────────
# `{token}` in https://api.lever.co/v0/postings/{token}
LEVER_BULK_TOKENS: tuple[tuple[str, str], ...] = (
    ("ableton", "Ableton"),
    ("affinity", "Affinity"),
    ("airwallex", "Airwallex"),
    ("algorand", "Algorand"),
    ("anaconda", "Anaconda"),
    ("animoca-brands", "Animoca Brands"),
    ("aparavi", "Aparavi"),
    ("appsmith", "Appsmith"),
    ("astralabs", "Astralabs"),
    ("atomicobject", "Atomic Object"),
    ("ava-labs", "Ava Labs"),
    ("bigbinary", "BigBinary"),
    ("bitpanda", "Bitpanda"),
    ("blockchain", "Blockchain.com"),
    ("blockstream", "Blockstream"),
    ("bluescape", "Bluescape"),
    ("brightwheel", "Brightwheel"),
    ("brilliant", "Brilliant"),
    ("cabify", "Cabify"),
    ("calibrate", "Calibrate"),
    ("cake", "Cake DeFi"),
    ("cardanofoundation", "Cardano Foundation"),
    ("celsiusnetwork", "Celsius Network"),
    ("centerforopenscience", "Center for Open Science"),
    ("checkr", "Checkr"),
    ("chubbiesshorts", "Chubbies"),
    ("clipboardhealth", "Clipboard Health"),
    ("coalition", "Coalition"),
    ("contraco", "Contra"),
    ("coursehero", "Course Hero"),
    ("creditkarma", "Credit Karma"),
    ("dailypay", "DailyPay"),
    ("damus", "Damus"),
    ("decagon", "Decagon"),
    ("deepmind", "DeepMind"),
    ("diem", "Diem"),
    ("docker", "Docker"),
    ("eightfold", "Eightfold AI"),
    ("everlaw", "Everlaw"),
    ("fanduel", "FanDuel"),
    ("forte", "Forte"),
    ("gemini-trust", "Gemini Trust Company"),
    ("genies", "Genies"),
    ("goat", "GOAT"),
    ("goldsky", "Goldsky"),
    ("gopuff", "Gopuff"),
    ("guideline", "Guideline"),
    ("handshake", "Handshake"),
    ("harness", "Harness"),
    ("hellosign", "HelloSign"),
    ("helpscout", "Help Scout"),
    ("hopper", "Hopper"),
    ("hover", "Hover"),
    ("imagen-technologies", "Imagen Technologies"),
    ("imply", "Imply"),
    ("incode", "Incode Technologies"),
    ("instabug", "Instabug"),
    ("inrupt", "Inrupt"),
    ("intellizencellc", "Intellizence"),
    ("invoca", "Invoca"),
    ("kindbody", "Kindbody"),
    ("klue", "Klue"),
    ("ladder", "Ladder"),
    ("lattice", "Lattice"),
    ("ledgerinvesting", "Ledger Investing"),
    ("lendingtree", "LendingTree"),
    ("liftoff", "Liftoff"),
    ("livekit", "LiveKit"),
    ("lookout", "Lookout"),
    ("mage", "Mage"),
    ("magicleap", "Magic Leap"),
    ("matterport", "Matterport"),
    ("medable", "Medable"),
    ("memora-health", "Memora Health"),
    ("messari", "Messari"),
    ("mode", "Mode Analytics"),
    ("moonbug", "Moonbug Entertainment"),
    ("moonpay", "MoonPay"),
    ("nerdwallet", "NerdWallet"),
    ("notarize", "Notarize"),
    ("nuna", "Nuna"),
    ("nylas-platform", "Nylas"),
    ("openexchange", "Open Exchange"),
    ("opentelemetry", "OpenTelemetry"),
    ("opentrons", "Opentrons"),
    ("particle", "Particle"),
    ("paystack", "Paystack"),
    ("pendo", "Pendo"),
    ("pleo", "Pleo"),
    ("policygenius", "Policygenius"),
    ("postmates", "Postmates"),
    ("primer", "Primer"),
    ("provi", "Provi"),
    ("puzzle", "Puzzle"),
    ("quartzy", "Quartzy"),
    ("quizlet", "Quizlet"),
    ("radix", "Radix"),
    ("ramp-financial", "Ramp"),
    ("range", "Range"),
    ("reddit", "Reddit"),
    ("relay-therapeutics", "Relay Therapeutics"),
    ("roivantsciences", "Roivant Sciences"),
    ("samsung-next", "Samsung NEXT"),
    ("scribehq", "Scribe"),
    ("secureframe", "Secureframe"),
    ("shieldai", "Shield AI"),
    ("shopmonkey", "Shopmonkey"),
    ("sigmacomputing", "Sigma Computing"),
    ("simplisafe", "SimpliSafe"),
    ("sketch", "Sketch"),
    ("sparklabs", "SparkLabs"),
    ("squarepoint", "Squarepoint Capital"),
    ("step", "Step"),
    ("stitch", "Stitch"),
    ("substack", "Substack"),
    ("supabase", "Supabase"),
    ("superblocks", "Superblocks"),
    ("tezos", "Tezos"),
    ("thumbtack", "Thumbtack"),
    ("tonal-fitness", "Tonal"),
    ("upside", "Upside"),
    ("urbansitter", "UrbanSitter"),
    ("varo", "Varo Bank"),
    ("vendia", "Vendia"),
    ("veritone", "Veritone"),
    ("vidyo", "Vidyo"),
    ("waabi", "Waabi"),
    ("warpdotdev", "Warp"),
    ("welcome", "Welcome"),
    ("wellsky", "WellSky"),
    ("workhuman", "Workhuman"),
    ("wrike", "Wrike"),
    ("yotpo", "Yotpo"),
    ("zaius", "Zaius"),
    ("zillow", "Zillow"),
    ("zoominfo-engineering", "ZoomInfo"),
)

# ── Ashby ───────────────────────────────────────────────────────────────────
# `{token}` in https://api.ashbyhq.com/posting-api/job-board/{token}.
# `ASHBY_KNOWN_TOKENS` in companies.py is the smaller curated baseline
# already seeded by migration 0010; this bulk list extends it.
ASHBY_BULK_TOKENS: tuple[tuple[str, str], ...] = (
    ("0x", "0x Labs"),
    ("aave", "Aave"),
    ("airplane", "Airplane"),
    ("airwallex", "Airwallex"),
    ("apollo", "Apollo"),
    ("arc-browser", "The Browser Company"),
    ("argentlabs", "Argent"),
    ("avara", "Avara"),
    ("baseten", "Baseten"),
    ("blockdaemon", "Blockdaemon"),
    ("blueprint-title", "Blueprint Title"),
    ("buildkite", "Buildkite"),
    ("captions", "Captions"),
    ("cardless-hq", "Cardless"),
    ("causal", "Causal"),
    ("chainalysis", "Chainalysis"),
    ("character-ai", "Character.AI"),
    ("clay", "Clay"),
    ("convex", "Convex"),
    ("cresta", "Cresta"),
    ("cursor", "Cursor"),
    ("dagster", "Dagster"),
    ("decagonai", "Decagon"),
    ("descript", "Descript"),
    ("digits", "Digits"),
    ("dust-tt", "Dust"),
    ("eppo", "Eppo"),
    ("eqtylabs", "EQTY Lab"),
    ("ethereumfoundation", "Ethereum Foundation"),
    ("exa", "Exa"),
    ("fivetran-eng", "Fivetran"),
    ("freed", "Freed"),
    ("gamma", "Gamma"),
    ("granola", "Granola"),
    ("groq", "Groq"),
    ("harvey", "Harvey"),
    ("huggingface", "Hugging Face"),
    ("inflection", "Inflection AI"),
    ("klaviyo-talent", "Klaviyo"),
    ("knot", "Knot"),
    ("lambda-labs", "Lambda Labs"),
    ("langchain", "LangChain"),
    ("liquibase", "Liquibase"),
    ("mantle", "Mantle"),
    ("matterai", "Matter AI"),
    ("mintlify", "Mintlify"),
    ("nansen", "Nansen"),
    ("notable", "Notable"),
    ("nuna-careers", "Nuna"),
    ("nuvolari", "Nuvolari"),
    ("obviousagency", "Obvious Agency"),
    ("openai", "OpenAI"),
    ("opus", "Opus"),
    ("origami", "Origami"),
    ("oso", "Oso"),
    ("pave", "Pave"),
    ("perplexityai", "Perplexity AI"),
    ("pika", "Pika"),
    ("polychain", "Polychain Capital"),
    ("prefect-io", "Prefect"),
    ("prelim", "Prelim"),
    ("rasa", "Rasa"),
    ("readyset", "ReadySet"),
    ("retool-eng", "Retool"),
    ("runway", "Runway"),
    ("scale-ai", "Scale AI"),
    ("speakai", "Speak"),
    ("stainless", "Stainless"),
    ("statsig-careers", "Statsig"),
    ("supabase-jobs", "Supabase"),
    ("temporalio", "Temporal"),
    ("tinybird", "Tinybird"),
    ("traba", "Traba"),
    ("tractian", "Tractian"),
    ("tract", "Tract"),
    ("twelvelabs", "Twelve Labs"),
    ("upstash", "Upstash"),
    ("vercel", "Vercel"),
    ("visible", "Visible"),
    ("warp", "Warp"),
    ("watershed", "Watershed"),
    ("worldcoin", "Worldcoin"),
    ("writer", "Writer"),
    ("xaihq", "xAI"),
)

# ── SmartRecruiters ─────────────────────────────────────────────────────────
# `{company}` in https://api.smartrecruiters.com/v1/companies/{company}/postings.
# These are CASE-SENSITIVE identifiers, NOT slugs — every entry below
# is the literal value SmartRecruiters expects (e.g. `Bosch`, not
# `bosch`). Cross-checked names that obviously diverge from a slug
# (e.g. `Visa1`) are preserved verbatim.
SMARTRECRUITERS_BULK_TOKENS: tuple[tuple[str, str], ...] = (
    ("Bosch", "Bosch"),
    ("Visa1", "Visa"),
    ("AvantStay", "AvantStay"),
    ("BoschGroup", "Bosch Group"),
    ("CaesarsEntertainment", "Caesars Entertainment"),
    ("CapcomUSA", "Capcom USA"),
    ("Coinbase", "Coinbase"),
    ("Compass1", "Compass"),
    ("Equinor", "Equinor"),
    ("Frasers", "Frasers Group"),
    ("HEINEKEN", "Heineken"),
    ("HelloFresh", "HelloFresh"),
    ("Ikea", "IKEA"),
    ("LVMH", "LVMH"),
    ("McDonalds", "McDonald's"),
    ("PublicisGroupe", "Publicis Groupe"),
    ("Squarespace1", "Squarespace"),
    ("UbisoftEntertainment", "Ubisoft"),
    ("WPP", "WPP"),
    ("Zalando1", "Zalando"),
)

# ── Workday ─────────────────────────────────────────────────────────────────
# `{tenant}:{dc}:{site}` packed into `sources.token`. Curated triples
# only — every entry below has the three components inferred from the
# company's public careers URL (`https://{tenant}.{dc}.myworkdayjobs.com/{site}`).
# Entries whose triple we couldn't pin down are deliberately OMITTED
# rather than guessed — the adapter would otherwise log a malformed-
# token error every pass for a row that's not going to resolve.
WORKDAY_BULK_TOKENS: tuple[tuple[str, str], ...] = (
    ("walmart:wd5:WalmartExternal", "Walmart"),
    ("nvidia:wd5:NVIDIAExternalCareerSite", "NVIDIA"),
    ("adobe:wd5:external_experienced", "Adobe"),
    ("autodesk:wd1:uex", "Autodesk"),
    ("capitalone:wd12:Capital_One", "Capital One"),
    ("cisco:wd5:External_Career_Site", "Cisco"),
    ("disney:wd5:disneycareer", "The Walt Disney Company"),
    ("flexport:wd1:Flexport_External_Careers", "Flexport"),
    ("ge:wd5:ge_externalsite", "GE"),
    ("hpe:wd5:Jobsathpe", "Hewlett Packard Enterprise"),
    ("ibm:wd5:IBM-Careers", "IBM"),
    ("intuit:wd5:IntuitExternalCareerSite", "Intuit"),
    ("jpmc:wd5:jpmc", "JPMorgan Chase"),
    ("kraftheinz:wd3:kraftheinz", "Kraft Heinz"),
    ("mastercard:wd1:CorporateCareers", "Mastercard"),
    ("netflix:wd1:Netflix_Careers", "Netflix"),
    ("paypal:wd1:jobs", "PayPal"),
    ("pepsico:wd5:PepsiCoJobs", "PepsiCo"),
    ("salesforce:wd12:External_Career_Site", "Salesforce"),
    ("ssga:wd1:SSGA_External", "State Street"),
    ("targetcorp:wd5:targetcareers", "Target"),
    ("tesla:wd5:Tesla", "Tesla"),
    ("ups:wd5:UPSJobs", "UPS"),
    ("verizon:wd5:verizon", "Verizon"),
    ("vmware:wd1:VMware", "VMware"),
)


def all_bulk_rows() -> dict[str, list[dict]]:
    """Return per-source-type lists of dicts ready for SQL insert. The
    migration assembles its insert payload by concatenating these
    lists; the test suite uses the per-platform breakdown to pin the
    counts."""
    return {
        "greenhouse": [
            {"source_type": "greenhouse", "token": tok, "display_name": name, "location": None}
            for tok, name in GREENHOUSE_BULK_TOKENS
        ],
        "lever": [
            {"source_type": "lever", "token": tok, "display_name": name, "location": None}
            for tok, name in LEVER_BULK_TOKENS
        ],
        "ashby": [
            {"source_type": "ashby", "token": tok, "display_name": name, "location": None}
            for tok, name in ASHBY_BULK_TOKENS
        ],
        "smartrecruiters": [
            {
                "source_type": "smartrecruiters",
                "token": tok,
                "display_name": name,
                "location": None,
            }
            for tok, name in SMARTRECRUITERS_BULK_TOKENS
        ],
        "workday": [
            {"source_type": "workday", "token": tok, "display_name": name, "location": None}
            for tok, name in WORKDAY_BULK_TOKENS
        ],
    }
